// Mocks generated by Mockito 5.4.0 from annotations
// in poke_app/test/features/pokemon_search/domain/usecases/get_pokemon_by_name_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:poke_app/core/entities/failure.dart' as _i5;
import 'package:poke_app/features/pokemon_search/domain/entities/pokemon_search.dart'
    as _i6;
import 'package:poke_app/features/pokemon_search/domain/repositories/pokemon_search_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonSearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonSearchRepository extends _i1.Mock
    implements _i3.PokemonSearchRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PokemonSearch>> getPokemonByName(
          String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonByName,
          [name],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.PokemonSearch>>.value(
                _FakeEither_0<_i5.Failure, _i6.PokemonSearch>(
          this,
          Invocation.method(
            #getPokemonByName,
            [name],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.PokemonSearch>>.value(
                _FakeEither_0<_i5.Failure, _i6.PokemonSearch>(
          this,
          Invocation.method(
            #getPokemonByName,
            [name],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.PokemonSearch>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PokemonSearch>> getPokemonById(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.PokemonSearch>>.value(
                _FakeEither_0<_i5.Failure, _i6.PokemonSearch>(
          this,
          Invocation.method(
            #getPokemonById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.PokemonSearch>>.value(
                _FakeEither_0<_i5.Failure, _i6.PokemonSearch>(
          this,
          Invocation.method(
            #getPokemonById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.PokemonSearch>>);
}
