// Mocks generated by Mockito 5.4.0 from annotations
// in poke_app/test/features/favorite_pokemon/domain/usecases/get_favorite_pokemon_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:poke_app/core/entities/pokemon.dart' as _i6;
import 'package:poke_app/core/error/failure.dart' as _i5;
import 'package:poke_app/features/favorite_pokemon/domain/repositories/favorite_pokemon_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FavoritePokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritePokemonRepository extends _i1.Mock
    implements _i3.FavoritePokemonRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Pokemon>> getFavoritePokemon(
          int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoritePokemon,
          [index],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Pokemon>>.value(
            _FakeEither_0<_i5.Failure, _i6.Pokemon>(
          this,
          Invocation.method(
            #getFavoritePokemon,
            [index],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Pokemon>>.value(
                _FakeEither_0<_i5.Failure, _i6.Pokemon>(
          this,
          Invocation.method(
            #getFavoritePokemon,
            [index],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Pokemon>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Pokemon>>>
      showFavoritePokemonList() => (super.noSuchMethod(
            Invocation.method(
              #showFavoritePokemonList,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Pokemon>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Pokemon>>(
              this,
              Invocation.method(
                #showFavoritePokemonList,
                [],
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Pokemon>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Pokemon>>(
              this,
              Invocation.method(
                #showFavoritePokemonList,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Pokemon>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> deleteFavoritePokemon(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFavoritePokemon,
          [index],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #deleteFavoritePokemon,
            [index],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, int>>.value(
                _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #deleteFavoritePokemon,
            [index],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);
}
