// Mocks generated by Mockito 5.4.0 from annotations
// in poke_app/test/features/pokemon_search/data/repositories/pokemon_search_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:poke_app/core/models/core_models.dart' as _i2;
import 'package:poke_app/core/network/network_info.dart' as _i5;
import 'package:poke_app/features/pokemon_search/data/datasources/pokemon_search_remote_data_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonModel_0 extends _i1.SmartFake implements _i2.PokemonModel {
  _FakePokemonModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonSearchRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonSearchRemoteDataSource extends _i1.Mock
    implements _i3.PokemonSearchRemoteDataSource {
  @override
  _i4.Future<_i2.PokemonModel> getPokemonById(int? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonById,
          [number],
        ),
        returnValue: _i4.Future<_i2.PokemonModel>.value(_FakePokemonModel_0(
          this,
          Invocation.method(
            #getPokemonById,
            [number],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PokemonModel>.value(_FakePokemonModel_0(
          this,
          Invocation.method(
            #getPokemonById,
            [number],
          ),
        )),
      ) as _i4.Future<_i2.PokemonModel>);
  @override
  _i4.Future<_i2.PokemonModel> getPokemonByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonByName,
          [name],
        ),
        returnValue: _i4.Future<_i2.PokemonModel>.value(_FakePokemonModel_0(
          this,
          Invocation.method(
            #getPokemonByName,
            [name],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PokemonModel>.value(_FakePokemonModel_0(
          this,
          Invocation.method(
            #getPokemonByName,
            [name],
          ),
        )),
      ) as _i4.Future<_i2.PokemonModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
